In [8]:
import numpy as np

In [166]:
gt = np.asarray([[[0,0,0,0,0,0,0,0,0],
                  [0,0,0,0,0,0,0,0,0],
                  [0,0,0,0,0,0,0,0,0],
                  [0,0,0,0,0,0,0,0,0],
                  [0,0,0,0,0,0,0,0,0]],
                 [[0,0,0,0,0,0,0,0,0],
                  [0,0,0,0,0,0,0,0,0],
                  [0,0,0,1,1,0,0,0,0],
                  [0,0,0,1,1,0,0,0,0],
                  [0,0,0,0,0,0,0,0,0]],
                 [[0,0,0,0,0,0,0,0,0],
                  [4,4,0,0,0,0,0,0,0],
                  [4,4,0,0,0,0,0,0,0],
                  [0,0,0,0,0,0,0,2,2],
                  [0,0,0,0,0,0,0,0,0]],
                 [[0,0,0,0,0,0,0,0,0],
                  [4,4,0,0,0,0,0,0,0],
                  [4,4,0,0,0,0,0,0,0],
                  [0,0,0,0,0,0,0,2,2],
                  [0,0,0,0,0,0,0,0,0]]])

gt = np.asarray([[[0,0,0,0,0],
                  [0,0,0,0,0],
                  [0,0,0,0,0],
                  [0,0,0,0,0],
                  [0,0,0,0,0]],
                 [[5,5,0,8,8],
                  [5,5,0,8,8],
                  [9,9,9,0,0],
                  [9,9,9,0,0],
                  [9,9,9,0,0]],
                 [[5,5,0,8,8],
                  [5,5,0,8,8],
                  [9,9,9,0,0],
                  [9,9,9,0,0],
                  [9,9,9,0,0]],
                 [[5,5,0,8,8],
                  [5,5,0,8,8],
                  [9,9,9,0,0],
                  [9,9,9,0,0],
                  [9,9,9,0,0]]])

# gt = np.ones((5,5,5))

In [185]:
pred = np.asarray([[[0,0,0,0,0,0,0,0,0],
                    [0,0,0,0,0,0,0,0,0],
                    [0,0,0,0,0,0,0,0,0],
                    [0,0,0,0,0,0,0,0,0],
                    [0,0,0,0,0,0,0,0,0]],
                   [[0,0,0,0,0,0,0,0,0],
                    [0,0,0,0,0,0,0,0,0],
                    [0,0,0,1,1,0,0,0,0],
                    [0,0,0,1,1,0,0,0,0],
                    [0,0,0,0,0,0,0,0,0]],
                   [[0,0,0,0,0,0,0,0,0],
                    [0,0,0,0,0,0,0,0,0],
                    [0,0,0,0,0,0,0,0,0],
                    [0,0,0,0,0,0,0,2,2],
                    [0,0,0,0,0,0,0,0,0]],
                   [[0,0,0,0,0,0,0,0,0],
                    [4,4,0,0,0,0,0,0,0],
                    [0,0,0,0,0,0,0,0,0],
                    [0,0,0,0,0,0,0,2,2],
                    [0,0,0,0,0,0,0,0,0]]])

pred = np.asarray([[[0,0,0,0,0],
                    [0,0,0,0,0],
                    [0,0,0,0,0],
                    [0,0,0,0,0],
                    [0,0,0,0,0]],
                   [[0,0,7,7,0],
                    [0,0,7,7,0],
                    [9,9,9,0,0],
                    [9,9,9,0,0],
                    [9,9,9,0,0]],
                   [[3,0,7,7,0],
                    [0,0,7,7,0],
                    [9,9,9,0,0],
                    [9,9,9,0,0],
                    [9,9,9,0,0]],
                   [[3,3,7,7,0],
                    [3,3,7,7,0],
                    [9,9,9,0,0],
                    [9,9,9,0,0],
                    [9,9,9,0,0]]])

# pred = np.ones((5,5,5))

In [186]:
import torch
def img_3d_interpolate(img_3d, output_size, device = torch.device('cpu'), mode='nearest'):
    img_3d = img_3d.reshape(1,1,img_3d.shape[0],img_3d.shape[1],img_3d.shape[2])
    img_3d=torch.from_numpy(img_3d).float().to(device)
    img_3d=torch.nn.functional.interpolate(img_3d, size=output_size, mode='nearest')
    img_3d=img_3d.detach().cpu().numpy()
    img_3d=img_3d.reshape(img_3d.shape[2],img_3d.shape[3],img_3d.shape[4])

    return img_3d

In [187]:
from func.cal_accuracy import IOU_and_Dice_Accuracy

output_size = pred.shape

accuracy=IOU_and_Dice_Accuracy(img_3d_interpolate(gt, output_size = output_size),
                                   img_3d_interpolate(pred, output_size = output_size))
accuracy_record=accuracy.cal_accuracy_II()
hand_seg_after_accuracy=accuracy.gt
seg_final_after_accuracy=accuracy.pred

In [191]:
hand_seg_after_accuracy

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[5., 5., 0., 8., 8.],
        [5., 5., 0., 8., 8.],
        [9., 9., 9., 0., 0.],
        [9., 9., 9., 0., 0.],
        [9., 9., 9., 0., 0.]],

       [[5., 5., 0., 8., 8.],
        [5., 5., 0., 8., 8.],
        [9., 9., 9., 0., 0.],
        [9., 9., 9., 0., 0.],
        [9., 9., 9., 0., 0.]],

       [[5., 5., 0., 8., 8.],
        [5., 5., 0., 8., 8.],
        [9., 9., 9., 0., 0.],
        [9., 9., 9., 0., 0.],
        [9., 9., 9., 0., 0.]]], dtype=float32)

In [192]:
seg_final_after_accuracy

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 8., 8., 0.],
        [0., 0., 8., 8., 0.],
        [9., 9., 9., 0., 0.],
        [9., 9., 9., 0., 0.],
        [9., 9., 9., 0., 0.]],

       [[5., 0., 8., 8., 0.],
        [0., 0., 8., 8., 0.],
        [9., 9., 9., 0., 0.],
        [9., 9., 9., 0., 0.],
        [9., 9., 9., 0., 0.]],

       [[5., 5., 8., 8., 0.],
        [5., 5., 8., 8., 0.],
        [9., 9., 9., 0., 0.],
        [9., 9., 9., 0., 0.],
        [9., 9., 9., 0., 0.]]], dtype=float32)

In [189]:
accuracy_record

array([[5.        , 0.5       , 0.66666669],
       [8.        , 0.5       , 0.66666669],
       [9.        , 1.        , 1.        ]])

In [190]:
np.max(pred)

9