In [4]:
from func.ultis import decompress_pickle, load_obj
import matplotlib.pyplot as plt

from func.run_pipeline_super_vox import reassign
import numpy as np
from func.plot_utils import colorful_seg, fill_noise

import napari
import h5py

In [ ]:
seg_final_eg_gcn = decompress_pickle("../../masterthesis_results/ovules_results/edge_gated/N_294_final_crop_ds2.npz_seg_final.pbz2")
seg_final_eg_gcn = fill_noise(seg_final_eg_gcn)
seg_final_eg_gcn_colorful = colorful_seg(seg_final_eg_gcn)

In [ ]:
seg_final_retrained = decompress_pickle("../../masterthesis_results/ovules_results/retrained/N_294_final_crop_ds2.npz_seg_final.pbz2")
seg_final_retrained_colorful = colorful_seg(seg_final_retrained)

In [ ]:
seg_final_gasp = decompress_pickle("../../masterthesis_results/ovules_results/gasp/N_294_final_crop_ds2.npz_seg_final.pbz2")
seg_final_gasp_colorful = colorful_seg(seg_final_gasp.astype(np.int32))

In [ ]:
hf = np.load("../data/CellSeg_dataset/Ovules_processed_thin_boundary_edge/test/N_294_final_crop_ds2.npz")
print(hf.keys())
raw_img = np.array(hf["raw"], dtype=np.float)
hand_seg = np.array(hf["ins"], dtype=np.float)
hand_seg_colorful = colorful_seg(hand_seg)

In [ ]:
N=80


plt.figure(figsize=(8, 6), dpi=200)
plt.title("raw")
plt.imshow(raw_img[:,N,:])

plt.figure(figsize=(8, 6), dpi=200)
plt.title("gt")
plt.imshow(reassign(hand_seg_colorful[:,N,:]))

plt.figure(figsize=(8, 6), dpi=200)
plt.title("seg_final eg cnn")
plt.imshow(reassign(seg_final_eg_gcn_colorful[:,N,:]))
# plt.savefig("outputs/final_seg_eg_gcn_LRP_1.pdf")

plt.figure(figsize=(8, 6), dpi=200)
plt.title("seg_final retrained")
plt.imshow(reassign(seg_final_retrained_colorful[:,N,:]))

plt.figure(figsize=(8, 6), dpi=200)
plt.title("seg_final gasp")
plt.imshow(reassign(seg_final_gasp_colorful[:,N,:]))

In [ ]:
N=80


plt.figure(figsize=(8, 6), dpi=200)
plt.title("raw")
plt.imshow(raw_img[N,:,:])

plt.figure(figsize=(8, 6), dpi=200)
plt.title("gt")
plt.imshow(reassign(hand_seg_colorful[N,:,:]))

plt.figure(figsize=(8, 6), dpi=200)
plt.title("seg_final eg cnn")
plt.imshow(reassign(seg_final_eg_gcn_colorful[N,:,:]))
# plt.savefig("outputs/final_seg_eg_gcn_LRP_1.pdf")

plt.figure(figsize=(8, 6), dpi=200)
plt.title("seg_final retrained")
plt.imshow(reassign(seg_final_retrained_colorful[N,:,:]))

plt.figure(figsize=(8, 6), dpi=200)
plt.title("seg_final gasp")
plt.imshow(reassign(seg_final_gasp_colorful[N,:,:]))

In [ ]:
seg_final_eg_gcn = decompress_pickle("../../masterthesis_results/ovules_results/edge_gated/N_294_final_crop_ds2.npz_seg_final.pbz2")
# start napari
viewer = napari.Viewer()

# show images
viewer.add_image(seg_final_eg_gcn)

In [ ]:

blobs = seg_final_eg_gcn# data.binary_blobs(length=128, volume_fraction=0.1, n_dim=3)
viewer = napari.view_image(blobs.astype(float), name='blobs')
labeled = seg_final_eg_gcn
viewer.add_labels(labeled, name='blob ID')

In [ ]:
blobs = seg_final_retrained# data.binary_blobs(length=128, volume_fraction=0.1, n_dim=3)
viewer = napari.view_image(blobs.astype(float), name='blobs')

In [ ]:
blobs = seg_final_retrained# data.binary_blobs(length=128, volume_fraction=0.1, n_dim=3)
viewer = napari.view_image(blobs.astype(float), name='blobs_retrained')
labeled = seg_final_retrained
viewer.add_labels(labeled, name='blob ID RETRAINED')

In [ ]:
blobs = seg_final_eg_gcn# data.binary_blobs(length=128, volume_fraction=0.1, n_dim=3)
viewer = napari.view_image(blobs.astype(float), name='blobs_eg')
labeled = seg_final_eg_gcn
viewer.add_labels(labeled, name='blob ID EG')

In [2]:
seg_final_retrained = decompress_pickle("../../masterthesis_results/ovules_results/retrained/N_294_final_crop_ds2.npz_seg_final.pbz2")


In [55]:
from napari_process_points_and_surfaces import label_to_surface, simplify_vertex_clustering, filter_smooth_taubin
from skimage.measure import regionprops
from napari_pymeshlab import colorize_curvature_apss


blobs = seg_final_retrained[:, 0:150, 0:150]
viewer = napari.view_image(blobs.astype(float), name='blobs_retrained')
labeled = seg_final_retrained[:, 0:150, 0:150]
viewer.add_labels(labeled, name='blob ID RETRAINED')

statistics = regionprops(labeled)
for i, r in enumerate(statistics):
    surface = label_to_surface(labeled, r.label)
    surface = filter_smooth_taubin(surface, 200)
    su_list = list(surface)
    # su_list[2] = np.linspace(0, 9999999999, len(su_list[0]))
    su_list[2] = np.ones_like(surface[2]) * r.label * 0.01
    surface = tuple(su_list)
    print(surface[2])
    surface_layer = viewer.add_surface(surface, blending='opaque', shading='smooth', colormap='label_colormap')
    if i >= 25:
        break

/opt/anaconda3/envs/CellSeg3D_torch/lib/python3.8/site-packages/napari/plugins/_plugin_manager.py:549: UserWarning: Plugin 'napari-time-slicer' has already registered a function widget 'convert to 2d timelapse' which has now been overwritten
  warn(message=warn_message)
/opt/anaconda3/envs/CellSeg3D_torch/lib/python3.8/site-packages/napari/plugins/_plugin_manager.py:549: UserWarning: Plugin 'napari-process-points-and-surfaces' has already registered a function widget 'convex hull' which has now been overwritten
  warn(message=warn_message)
/opt/anaconda3/envs/CellSeg3D_torch/lib/python3.8/site-packages/napari/plugins/_plugin_manager.py:549: UserWarning: Plugin 'napari-process-points-and-surfaces' has already registered a function widget 'filter smooth simple' which has now been overwritten
  warn(message=warn_message)
/opt/anaconda3/envs/CellSeg3D_torch/lib/python3.8/site-packages/napari/plugins/_plugin_manager.py:549: UserWarning: Plugin 'napari-process-points-and-surfaces' has alread

[0.12 0.12 0.12 ... 0.12 0.12 0.12]
[0.19 0.19 0.19 ... 0.19 0.19 0.19]
[0.21 0.21 0.21 ... 0.21 0.21 0.21]
[0.25 0.25 0.25 ... 0.25 0.25 0.25]
[0.36 0.36 0.36 ... 0.36 0.36 0.36]
[0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38
 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38
 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38
 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38
 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38
 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38
 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38
 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38
 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38
 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38
 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.38
 0.38 0.38 0.38 0.38 0.38 0.38 0.38 0.3

In [11]:
for r in statistics:
    print(r.label)

12
19
21
25
36
38
42
43
48
51
55
68
70
75
79
87
100
101
108
109
121
123
124
125
129
134
139
163
169
170
192
207
208
212
223
225
232
233
234
236
237
238
249
251
253
254
259
271
285
306
308
309
312
314
328
329
347
350
354
356
376
377
388
389
390
391
392
394
396
417
421
422
423
425
426
453
454
455
456
457
458
460
495
498
499
501
528
529
531
532
535
536
568
569
570
571
590
591
592
593
595
596
597
598
617
619
620
643
647
648
649
650
651
653
654
669
670
672
673
675
677
678
679
680
711
713
715
718
720
721
752
754
755
756
757
758
759
761
762
763
764
792
793
794
795
796
803
804
805
806
807
808
809
810
852
853
857
858
859
860
861
862
881
882
883
884
887
888
912
916
920
938
943
971
972
973
974
976
977
979
1018
1022
1023
1024
1060
1061
1063
1064
1065
1066
1068
1070
1071
1074
1075
1076
1077
1078
1081
1082
1123
1124
1125
1126
1127
1128
1131
1132
1133
1134
1135
1136
1138
1139
1141
1142
1143
1144
1177
1179
1180
1181
1182
1183
1184
1186
1221
1223
1226
1227
1228
1229
1251
1252
1253
1256
1257
1259
1289
1

In [27]:

list(napari.utils.colormaps.AVAILABLE_COLORMAPS)

['PiYG',
 'blue',
 'bop blue',
 'bop orange',
 'bop purple',
 'cyan',
 'gist_earth',
 'gray',
 'gray_r',
 'green',
 'hsv',
 'inferno',
 'magenta',
 'magma',
 'plasma',
 'red',
 'turbo',
 'twilight',
 'twilight_shifted',
 'viridis',
 'yellow',
 'label_colormap']